# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hdf5_browser_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HDF5BrowserWidget(object):
    def setupUi(self, HDF5BrowserWidget):
        HDF5BrowserWidget.setObjectName("HDF5BrowserWidget")
        HDF5BrowserWidget.resize(522, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(HDF5BrowserWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_filename = QtWidgets.QLabel(HDF5BrowserWidget)
        self.label_filename.setObjectName("label_filename")
        self.verticalLayout.addWidget(self.label_filename)
        self.treeWidget = QtWidgets.QTreeWidget(HDF5BrowserWidget)
        self.treeWidget.setProperty("headerLabels", ['Nom', 'Type', 'Chemin'])
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)
        self.layoutCube = QtWidgets.QHBoxLayout()
        self.layoutCube.setObjectName("layoutCube")
        self.labelCube = QtWidgets.QLabel(HDF5BrowserWidget)
        self.labelCube.setObjectName("labelCube")
        self.layoutCube.addWidget(self.labelCube)
        self.le_cube = QtWidgets.QLineEdit(HDF5BrowserWidget)
        self.le_cube.setReadOnly(True)
        self.le_cube.setObjectName("le_cube")
        self.layoutCube.addWidget(self.le_cube)
        self.btn_select_cube = QtWidgets.QPushButton(HDF5BrowserWidget)
        self.btn_select_cube.setObjectName("btn_select_cube")
        self.layoutCube.addWidget(self.btn_select_cube)
        self.verticalLayout.addLayout(self.layoutCube)
        self.layoutWl = QtWidgets.QHBoxLayout()
        self.layoutWl.setObjectName("layoutWl")
        self.labelWl = QtWidgets.QLabel(HDF5BrowserWidget)
        self.labelWl.setObjectName("labelWl")
        self.layoutWl.addWidget(self.labelWl)
        self.le_wl = QtWidgets.QLineEdit(HDF5BrowserWidget)
        self.le_wl.setReadOnly(True)
        self.le_wl.setObjectName("le_wl")
        self.layoutWl.addWidget(self.le_wl)
        self.btn_select_wl = QtWidgets.QPushButton(HDF5BrowserWidget)
        self.btn_select_wl.setObjectName("btn_select_wl")
        self.layoutWl.addWidget(self.btn_select_wl)
        self.verticalLayout.addLayout(self.layoutWl)
        self.layoutMeta = QtWidgets.QHBoxLayout()
        self.layoutMeta.setObjectName("layoutMeta")
        self.labelMeta = QtWidgets.QLabel(HDF5BrowserWidget)
        self.labelMeta.setObjectName("labelMeta")
        self.layoutMeta.addWidget(self.labelMeta)
        self.le_meta = QtWidgets.QLineEdit(HDF5BrowserWidget)
        self.le_meta.setReadOnly(True)
        self.le_meta.setObjectName("le_meta")
        self.layoutMeta.addWidget(self.le_meta)
        self.btn_select_meta = QtWidgets.QPushButton(HDF5BrowserWidget)
        self.btn_select_meta.setObjectName("btn_select_meta")
        self.layoutMeta.addWidget(self.btn_select_meta)
        self.verticalLayout.addLayout(self.layoutMeta)
        self.layoutButtons = QtWidgets.QHBoxLayout()
        self.layoutButtons.setObjectName("layoutButtons")
        self.label_wl_dim = QtWidgets.QLabel(HDF5BrowserWidget)
        self.label_wl_dim.setObjectName("label_wl_dim")
        self.layoutButtons.addWidget(self.label_wl_dim)
        self.comboBox_channel_wl = QtWidgets.QComboBox(HDF5BrowserWidget)
        self.comboBox_channel_wl.setObjectName("comboBox_channel_wl")
        self.comboBox_channel_wl.addItem("")
        self.comboBox_channel_wl.addItem("")
        self.layoutButtons.addWidget(self.comboBox_channel_wl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutButtons.addItem(spacerItem)
        self.btn_ok = QtWidgets.QPushButton(HDF5BrowserWidget)
        self.btn_ok.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.btn_ok.setObjectName("btn_ok")
        self.layoutButtons.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(HDF5BrowserWidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.layoutButtons.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.layoutButtons)

        self.retranslateUi(HDF5BrowserWidget)
        QtCore.QMetaObject.connectSlotsByName(HDF5BrowserWidget)

    def retranslateUi(self, HDF5BrowserWidget):
        _translate = QtCore.QCoreApplication.translate
        HDF5BrowserWidget.setWindowTitle(_translate("HDF5BrowserWidget", "Navigateur HDF5"))
        self.label_filename.setText(_translate("HDF5BrowserWidget", "File"))
        self.labelCube.setText(_translate("HDF5BrowserWidget", "Cube path :"))
        self.btn_select_cube.setText(_translate("HDF5BrowserWidget", "→ Cube"))
        self.labelWl.setText(_translate("HDF5BrowserWidget", "Wavelength path"))
        self.btn_select_wl.setText(_translate("HDF5BrowserWidget", "→ Wavelength"))
        self.labelMeta.setText(_translate("HDF5BrowserWidget", "Metadata Path :"))
        self.btn_select_meta.setText(_translate("HDF5BrowserWidget", "→ Metadata"))
        self.label_wl_dim.setText(_translate("HDF5BrowserWidget", "wl dim : "))
        self.comboBox_channel_wl.setItemText(0, _translate("HDF5BrowserWidget", "Last"))
        self.comboBox_channel_wl.setItemText(1, _translate("HDF5BrowserWidget", "First"))
        self.btn_ok.setText(_translate("HDF5BrowserWidget", "OK"))
        self.btn_cancel.setText(_translate("HDF5BrowserWidget", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HDF5BrowserWidget = QtWidgets.QWidget()
    ui = Ui_HDF5BrowserWidget()
    ui.setupUi(HDF5BrowserWidget)
    HDF5BrowserWidget.show()
    sys.exit(app.exec_())
