# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Save_Window(object):
    def setupUi(self, Save_Window):
        Save_Window.setObjectName("Save_Window")
        Save_Window.resize(423, 303)
        self.gridLayout_3 = QtWidgets.QGridLayout(Save_Window)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_save_cube_final = QtWidgets.QPushButton(Save_Window)
        self.pushButton_save_cube_final.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.pushButton_save_cube_final.setObjectName("pushButton_save_cube_final")
        self.gridLayout_3.addWidget(self.pushButton_save_cube_final, 4, 1, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(Save_Window)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout_3.addWidget(self.pushButton_Cancel, 4, 0, 1, 1)
        self.groupBox_hypercube_save_option = QtWidgets.QGroupBox(Save_Window)
        self.groupBox_hypercube_save_option.setObjectName("groupBox_hypercube_save_option")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_hypercube_save_option)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_only_aligned_save = QtWidgets.QRadioButton(self.groupBox_hypercube_save_option)
        self.radioButton_only_aligned_save.setChecked(True)
        self.radioButton_only_aligned_save.setObjectName("radioButton_only_aligned_save")
        self.gridLayout.addWidget(self.radioButton_only_aligned_save, 2, 0, 1, 1)
        self.radioButton_both_cube_save = QtWidgets.QRadioButton(self.groupBox_hypercube_save_option)
        self.radioButton_both_cube_save.setObjectName("radioButton_both_cube_save")
        self.gridLayout.addWidget(self.radioButton_both_cube_save, 2, 1, 1, 1)
        self.checkBox_minicube_save = QtWidgets.QCheckBox(self.groupBox_hypercube_save_option)
        self.checkBox_minicube_save.setObjectName("checkBox_minicube_save")
        self.gridLayout.addWidget(self.checkBox_minicube_save, 1, 0, 1, 1)
        self.comboBox_cube_format = QtWidgets.QComboBox(self.groupBox_hypercube_save_option)
        self.comboBox_cube_format.setObjectName("comboBox_cube_format")
        self.comboBox_cube_format.addItem("")
        self.comboBox_cube_format.addItem("")
        self.comboBox_cube_format.addItem("")
        self.gridLayout.addWidget(self.comboBox_cube_format, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_hypercube_save_option, 0, 0, 1, 2)
        self.groupBox_images_save_options = QtWidgets.QGroupBox(Save_Window)
        self.groupBox_images_save_options.setObjectName("groupBox_images_save_options")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_images_save_options)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_export_images = QtWidgets.QCheckBox(self.groupBox_images_save_options)
        self.checkBox_export_images.setObjectName("checkBox_export_images")
        self.gridLayout_2.addWidget(self.checkBox_export_images, 0, 0, 1, 1)
        self.radioButton_gray_save_image = QtWidgets.QRadioButton(self.groupBox_images_save_options)
        self.radioButton_gray_save_image.setChecked(True)
        self.radioButton_gray_save_image.setObjectName("radioButton_gray_save_image")
        self.gridLayout_2.addWidget(self.radioButton_gray_save_image, 1, 0, 1, 1)
        self.radioButton_RGB_save_image = QtWidgets.QRadioButton(self.groupBox_images_save_options)
        self.radioButton_RGB_save_image.setObjectName("radioButton_RGB_save_image")
        self.gridLayout_2.addWidget(self.radioButton_RGB_save_image, 1, 1, 1, 1)
        self.comboBox_image_format = QtWidgets.QComboBox(self.groupBox_images_save_options)
        self.comboBox_image_format.setObjectName("comboBox_image_format")
        self.comboBox_image_format.addItem("")
        self.comboBox_image_format.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_image_format, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_images_save_options, 1, 0, 1, 2)
        self.checkBox_modif_metadata = QtWidgets.QCheckBox(Save_Window)
        self.checkBox_modif_metadata.setObjectName("checkBox_modif_metadata")
        self.gridLayout_3.addWidget(self.checkBox_modif_metadata, 2, 0, 1, 2)

        self.retranslateUi(Save_Window)
        QtCore.QMetaObject.connectSlotsByName(Save_Window)

    def retranslateUi(self, Save_Window):
        _translate = QtCore.QCoreApplication.translate
        Save_Window.setWindowTitle(_translate("Save_Window", "Saving options"))
        self.pushButton_save_cube_final.setText(_translate("Save_Window", "Save cube(s)"))
        self.pushButton_Cancel.setText(_translate("Save_Window", "Cancel"))
        self.groupBox_hypercube_save_option.setTitle(_translate("Save_Window", "Hypercube save options"))
        self.radioButton_only_aligned_save.setText(_translate("Save_Window", "Only Aligned"))
        self.radioButton_both_cube_save.setText(_translate("Save_Window", "Both Cubes"))
        self.checkBox_minicube_save.setText(_translate("Save_Window", "Croped cubes"))
        self.comboBox_cube_format.setItemText(0, _translate("Save_Window", "HDF5 "))
        self.comboBox_cube_format.setItemText(1, _translate("Save_Window", "ENVI"))
        self.comboBox_cube_format.setItemText(2, _translate("Save_Window", "MATLAB"))
        self.groupBox_images_save_options.setTitle(_translate("Save_Window", "Images exportation"))
        self.checkBox_export_images.setText(_translate("Save_Window", "Export Images"))
        self.radioButton_gray_save_image.setText(_translate("Save_Window", "Gray"))
        self.radioButton_RGB_save_image.setText(_translate("Save_Window", "(False) RGB"))
        self.comboBox_image_format.setItemText(0, _translate("Save_Window", "PNG"))
        self.comboBox_image_format.setItemText(1, _translate("Save_Window", "JPG"))
        self.checkBox_modif_metadata.setText(_translate("Save_Window", "Add/Change Metadatas before saving"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Save_Window = QtWidgets.QWidget()
    ui = Ui_Save_Window()
    ui.setupUi(Save_Window)
    Save_Window.show()
    sys.exit(app.exec_())
