# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_cube_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(913, 468)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_load_cube_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_load_cube_2.setObjectName("pushButton_load_cube_2")
        self.gridLayout.addWidget(self.pushButton_load_cube_2, 3, 2, 1, 1)
        self.label_spectral_range = QtWidgets.QLabel(self.frame)
        self.label_spectral_range.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_spectral_range.setObjectName("label_spectral_range")
        self.gridLayout.addWidget(self.label_spectral_range, 1, 1, 1, 1)
        self.label_filepath_cube_1 = QtWidgets.QLabel(self.frame)
        self.label_filepath_cube_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_filepath_cube_1.setObjectName("label_filepath_cube_1")
        self.gridLayout.addWidget(self.label_filepath_cube_1, 2, 0, 1, 1)
        self.label_filepaths = QtWidgets.QLabel(self.frame)
        self.label_filepaths.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_filepaths.setObjectName("label_filepaths")
        self.gridLayout.addWidget(self.label_filepaths, 1, 0, 1, 1)
        self.label_spec_range_cube_2 = QtWidgets.QLabel(self.frame)
        self.label_spec_range_cube_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_spec_range_cube_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spec_range_cube_2.setObjectName("label_spec_range_cube_2")
        self.gridLayout.addWidget(self.label_spec_range_cube_2, 3, 1, 1, 1)
        self.label_spec_range_cube_1 = QtWidgets.QLabel(self.frame)
        self.label_spec_range_cube_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_spec_range_cube_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spec_range_cube_1.setObjectName("label_spec_range_cube_1")
        self.gridLayout.addWidget(self.label_spec_range_cube_1, 2, 1, 1, 1)
        self.pushButton_load_cube_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_load_cube_1.setObjectName("pushButton_load_cube_1")
        self.gridLayout.addWidget(self.pushButton_load_cube_1, 2, 2, 1, 1)
        self.label_filepath_cube_2 = QtWidgets.QLabel(self.frame)
        self.label_filepath_cube_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_filepath_cube_2.setObjectName("label_filepath_cube_2")
        self.gridLayout.addWidget(self.label_filepath_cube_2, 3, 0, 1, 1)
        self.label_instructions = QtWidgets.QLabel(self.frame)
        self.label_instructions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_instructions.setObjectName("label_instructions")
        self.gridLayout.addWidget(self.label_instructions, 5, 0, 1, 3)
        self.pushButton_valid = QtWidgets.QPushButton(self.frame)
        self.pushButton_valid.setObjectName("pushButton_valid")
        self.gridLayout.addWidget(self.pushButton_valid, 6, 0, 1, 3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_load_cube_2.setText(_translate("Dialog", "Load second cube"))
        self.label_spectral_range.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Spectral range</span></p></body></html>"))
        self.label_filepath_cube_1.setText(_translate("Dialog", "path cube"))
        self.label_filepaths.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Filepath of cube</span></p></body></html>"))
        self.label_spec_range_cube_2.setText(_translate("Dialog", "range"))
        self.label_spec_range_cube_1.setText(_translate("Dialog", "range"))
        self.pushButton_load_cube_1.setText(_translate("Dialog", "Load first cube"))
        self.label_filepath_cube_2.setText(_translate("Dialog", "path cube"))
        self.label_instructions.setText(_translate("Dialog", "Instructions"))
        self.pushButton_valid.setText(_translate("Dialog", "Valid cubes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
